### PR TITLE
Image width and height should not be forced in the component.

### PR DESCRIPTION
**Pull request by mvsusp**
- The library should no be responsible to resize the component.

### CODE REVIEW

**Comment by teleject** [comment]
@mvsusp can you clarify or describe what happens in Safari that happens with the existing code?

**Comment by Seneral** [comment]
@teleject Have the same problem @mvsusp seems to have removed these lines for. 

When you resize the browser window, the images loaded with hiSrc experience strange stretching artifacts im my case. Here's a gif showing the problem ('wrong behaviour'):
hisrcresizedproblem
Reloading the page resets the images of course, but when resizing again it's still stretched.
This seems to be caused by the added width and height attributes after loading, which are specified with fixed pixels and overwrite the relative css width and height properties (but not maxWidth = 100%, hence the stretching here).
Removing these lines fixed the problem and yields the 'fixed behaviour'.

You might consider removing them too, but I can't test in Safari to see what they are supposed to fix, unfortunately. Any chance you can work around that? For now I'll simply comment these lines.
Thanks!

**Comment by mvsusp** [comment]
@Seneral is right @teleject. That is the same issue that I experienced.

**Comment by teleject** [comment]
Cool. Thanks for the clarification, @Seneral and @mvsusp. Will look into it when I get a moment and more than likely update the code!

**Comment by mvsusp** [comment]
Thanks man!

**Comment by Seneral** [comment]
Great, thanks!

Also made some other changes #8 since then which solves some implementation issues of the speed test. 
Did some other changes too though which may be my mere own opinion, but seem alot more apropriate to me;)

**Pull request merged**
